### ISSUE TITLE
[ClassCastException: lib.model.Category$Color$GREEN$ cannot be cast to lib.model.Category$Color]

### ISSUE THREAD

**Issue by flutcla** [flutcla/todo-app#4]
一覧にアクセスすると時々 `[ClassCastException: lib.model.Category$Color$GREEN$ cannot be cast to lib.model.Category$Color]` と怒られる。毎回ではない。
sbt を再起動すると治る。

```scala
In .../todo-app/app/lib/persistence/db/Category.scala:48
44    // DB <=> Scala の相互マッピング
45    def * = (id.?, name, slug, color, updatedAt, createdAt) <> (
46      // Tuple => Model
47      (t: TableElementTuple) => Category(
48        t._1, t._2, t._3, t._4, t._5, t._6
49      ),
50      // Model => Tuple
51      (v: TableElementType) => Category.unapply(v).map { t => (
52        t._1, t._2, t._3, t._4, LocalDateTime.now(), t._6
```

**Comment by flutcla** [comment]
スタックトレース
```
[error] l.p.package$onMySQL$CategoryRepository$ - The database action failed. dsn=ixias.db.mysql://slave/to_do
java.lang.ClassCastException: lib.model.Category$Color$GREEN$ cannot be cast to lib.model.Category$Color
        at lib.persistence.db.CategoryTable$Table.$anonfun$$times$1(Category.scala:48)
        at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:133)
        at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36)
        at slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:66)
        at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
        at slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:28)
        at slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:34)
        at slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:33)
        at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] p.a.h.DefaultHttpErrorHandler - 

! @824f353gm - Internal server error, for (GET) [/todo/list] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ClassCastException: lib.model.Category$Color$GREEN$ cannot be cast to lib.model.Category$Color]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:332)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:251)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:421)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:417)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: java.lang.ClassCastException: lib.model.Category$Color$GREEN$ cannot be cast to lib.model.Category$Color
        at lib.persistence.db.CategoryTable$Table.$anonfun$$times$1(Category.scala:48)
        at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:133)
        at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36)
        at slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:66)
        at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
        at slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:28)
        at slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:34)
        at slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:33)
        at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
```

**Comment by flutcla** [comment]
Category の Color を `java.awt.Color` を利用し `Enum` を使わないことにしたので **Color に関しては** 解決
